---
- name: Delete rabbitmq cluster
  kubernetes.core.k8s:
    api_version: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    name: rabbitmq
    namespace: rabbitmq
    state: absent

- name: Uninstall rabbitmq
  kubernetes.core.helm:
    name: rabbitmq
    namespace: rabbitmq
    state: absent

- name: Remove rabbitmq helm repository
  kubernetes.core.helm_repository:
    name: bitnami
    state: absent

- name: Delete rabbitmq namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: rabbitmq
    state: absent

- name: Uninstall keda
  kubernetes.core.helm:
    name: keda
    namespace: keda
    state: absent

- name: Remove kedacore helm repository
  kubernetes.core.helm_repository:
    name: kedacore
    state: absent

- name: Delete keda namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: keda
    state: absent

- name: Delete cli
  become: yes
  file:
    path: '/usr/local/bin/fission'
    state: absent

- name: Uninstall fission
  kubernetes.core.helm:
    name: fission
    namespace: fission
    state: absent

- name: Remove helm repository
  kubernetes.core.helm_repository:
    name: fission-charts
    state: absent

- name: Delete crds
  command: kubectl delete -k "github.com/fission/fission/crds/v1?ref={{ fission_version }}"
  register: result
  failed_when: 
  - result.rc != 0
  - "'NotFound' not in result.stderr"

- name: Delete namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: fission
    state: absent