---
- name: delete /etc/sysctl.d/k8s.conf
  ansible.builtin.file:
    path: /etc/sysctl.d/k8s.conf
    state: absent

- name: reload sysctl
  ansible.builtin.command:
    cmd: sysctl --system
  become: yes

- name: uninstall packages needed to use the custom apt repositories
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - apt-utils
    - apt-transport-https
    - ca-certificates
    - gpg
    - curl
    - software-properties-common
