---
- name: Uninstall packages needed to use the custom apt repositories
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gpg
