---
# https://chaos-mesh.org/docs/production-installation-using-helm/
- name: add chaos mesh helm repository
  kubernetes.core.helm_repository:
    name: chaos-mesh
    repo_url: "https://charts.chaos-mesh.org"

- name: create chaos-mesh namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: chaos-mesh
    state: present

- name: install chaos mesh
  kubernetes.core.helm:
    name: chaos-mesh
    chart_ref: chaos-mesh/chaos-mesh
    release_namespace: chaos-mesh
    values:
      chaosDaemon:
        runtime: crio
        socketPath: /var/run/crio/crio.sock
      controllerManager:
        enableFilterNamespace: true
      version: "{{ chaos_mesh_version }}"

- name: enable chaos mesh in default namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: default
    definition:
      metadata:
        annotations:
          chaos-mesh.org/inject: enabled
    state: patched
  
- name: render template to access chaos dashboard remotely
  template:
    src: chaos-dashboard.j2
    dest: $HOME/chaos-dashboard.yaml

- name: create gateway and virtual service to access chaos dashboard remotely
  kubernetes.core.k8s:
    src: $HOME/chaos-dashboard.yaml
    state: present

- name: copy rbac for manager profile in default namespace
  copy:
    src: chaos-rbac.yaml
    dest: $HOME/chaos-rbac.yaml

- name: create manager profile in default namespace
  kubernetes.core.k8s:
    src: $HOME/chaos-rbac.yaml
    state: present
