---
- name: Download helm installer
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: $HOME/get-helm-3.sh
    mode: '0700'

- name: Install helm
  command: $HOME/get-helm-3.sh