---
- hosts: masters
  become: no
  tags:
  - chaos
  roles:
  - rollback/chaos-mesh

- hosts: masters
  become: no
  tags:
  - telemetry
  roles:
  - rollback/metrics-server
  - rollback/istio/addons

- hosts: masters
  become: no
  tags:
  - mesh
  roles:
  - rollback/istio

- hosts: masters
  become: no
  tags:
  - helm
  roles:
  - rollback/helm

- hosts: workers
  become: yes
  tags:
  - join
  roles:
  - rollback/k8s/join

- hosts: masters
  become: yes
  tags:
  - init
  roles:
  - rollback/nvidia/k8s
  - rollback/flannel
  - rollback/k8s/init

- hosts: gpus
  become: yes
  tags:
  - setup
  roles:
  - rollback/nvidia/crio

- hosts: all
  become: yes
  tags:
  - setup
  roles:
  - rollback/cni
  - rollback/k8s/common
  - rollback/crio
  - rollback/common
