---
- hosts:
  - masters
  - workers
  become: yes
  tags:
  - setup
  roles:
  - common
  - crio
  - k8s/common
  - cni

- hosts: controllers
  become: yes
  tags:
  - setup
  roles:
  - common
  - k8s/common

- hosts: gpus
  become: yes
  tags:
  - setup
  roles:
  - nvidia/crio

- hosts: masters
  become: yes
  tags:
  - init
  roles:
  - k8s/init
  - flannel
  - nvidia/k8s

- hosts: controllers
  become: no
  tags:
  - init
  roles:
  - k8s/remote

- hosts: workers
  become: yes
  tags:
  - join
  roles:
  - k8s/join

- hosts: 
  - masters
  - controllers
  become: no
  tags:
  - helm
  roles:
  - helm

- hosts: masters
  become: no
  tags:
  - mesh
  roles:
  - istio

- hosts: masters
  become: no
  tags:
  - telemetry
  roles:
  - metrics-server
  - kube-state-metrics
  - istio/addons

- hosts: masters
  become: no
  tags:
  - chaos
  roles:
  - chaos-mesh

- hosts: masters
  become: no
  tags:
  - serverless
  roles:
  - fission

- hosts: controllers
  become: no
  tags:
  - serverless
  roles:
  - fission/remote