---
- hosts: all
  become: yes
  tags:
  - setup
  roles:
  - common
  - crio
  - k8s/common

- hosts: masters
  become: yes
  tags:
  - init
  roles:
  - k8s/init
  - flannel

- hosts: workers
  become: yes
  tags:
  - join
  roles:
  - k8s/join
