---
- hosts: all
  become: yes
  tags:
  - setup
  roles:
  - common
  - crio
  - k8s/common
  - cni

- hosts: gpus
  become: yes
  tags:
  - setup
  roles:
  - nvidia/crio

- hosts: masters
  become: yes
  tags:
  - init
  roles:
  - k8s/init
  - flannel
  - nvidia/k8s

- hosts: workers
  become: yes
  tags:
  - join
  roles:
  - k8s/join

- hosts: masters
  become: no
  tags:
  - helm
  roles:
  - helm

- hosts: masters
  become: no
  tags:
  - mesh
  roles:
  - istio

- hosts: masters
  become: no
  tags:
  - telemetry
  roles:
  - metrics-server
  - istio/addons

- hosts: masters
  become: no
  tags:
  - chaos
  roles:
  - chaos-mesh

- hosts: masters
  become: no
  tags:
  - fission
  roles:
  - fission