---
- name: drain node
  become: no
  shell: >
    kubectl drain {{ hostvars[inventory_hostname]['ansible_hostname'] }}
    --force
    --ignore-daemonsets
  delegate_to: "{{ groups['masters'][0] }}"

- name: reset worker node
  shell: >
    kubeadm reset
    --cri-socket={{ cri_socket }}
    --force

- name: reset iptables
  shell: |
    iptables -F
    iptables -t nat -F
    iptables -t mangle -F
    iptables -X

- name: delete /etc/default/kubelet
  file:
    path: /etc/default/kubelet
    state: absent

- name: delete node
  become: no
  kubernetes.core.k8s:
    kind: Node
    name: "{{ hostvars[inventory_hostname]['ansible_hostname'] }}" 
    state: absent
  delegate_to: "{{ groups['masters'][0] }}"

- name: delete flannel.1 interface
  shell: ip link delete flannel.1
  register: del_flannel
  failed_when:
  - del_flannel.rc != 0
  - "'Cannot find device \"flannel.1\"' not in del_flannel.stderr"
  changed_when:
  - del_flannel.rc == 0

- name: delete cni0 bridge
  shell: ip link delete cni0 type bridge
  register: del_cni
  failed_when:
  - del_cni.rc != 0
  - "'Cannot find device \"cni0\"' not in del_cni.stderr"
  changed_when:
  - del_cni.rc == 0

- name: delete /run/flannel
  file:
    path: /run/flannel
    state: absent
