---
- name: Create join command
  shell: kubeadm token create --print-join-command
  register: join_cmd
  delegate_to: "{{ groups['masters'][0] }}"

- name: Ensure node has not joined yet
  become: no
  kubernetes.core.k8s_info:
    kind: Node
    name: "{{ hostvars[inventory_hostname]['ansible_hostname'] }}"
  register: k8s_node
  delegate_to: "{{ groups['masters'][0] }}"

- name: Join cluster
  block:
  - name: Run join command
    shell: "{{ join_cmd.stdout_lines[0] }} --cri-socket={{ cri_socket }}"
    when:
    - k8s_node.resources == []

  - name: Check if node joined
    become: no
    kubernetes.core.k8s_info:
      kind: Node
      name: "{{ ansible_hostname }}"
    register: k8s_node
    delegate_to: "{{ groups['masters'][0] }}"
    until:
    - k8s_node.resources != []
    retries: 60
    delay: 5

  - name: Check if status node is ready
    become: no
    kubernetes.core.k8s_info:
      kind: Node
      name: "{{ ansible_hostname }}"
      wait: yes
      wait_timeout: 300
      wait_condition:
        status: "True"
        type: "Ready"
    delegate_to: "{{ groups['masters'][0] }}"

- name: Create /etc/default/kubelet to set --node-ip
  lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ kubelet_node_ip }}
    create: true

- name: Restart service kubelet
  systemd:
    daemon_reload: yes
    name: kubelet
    state: restarted
