---
- name: uninstall kubelet, kubeadm, and kubectl
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl

- name: delete /etc/apt/sources.list.d/kubernetes.list
  file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: absent

- name: delete /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: absent

- name: delete /tmp/kubernetes-release.key
  file:
    path: /tmp/kubernetes-release.key
    state: absent

- name: enable swap
  shell: swapon -a
