---
- name: Uninstall kubelet, kubeadm, and kubectl
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl

- name: Remove k8s apt repository
  apt_repository:
    repo: |
      deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] 
      https://pkgs.k8s.io/core:/stable:/{{kubernetes_version_repo}}/{{kubernetes_os}}/ /
    filename: kubernetes
    state: absent

- name: Delete k8s public signing key
  file:
    path: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    state: absent

- name: Enable swap
  shell: swapon -a
