---
# https://github.com/NVIDIA/k8s-device-plugin
# https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
- name: dowload nvidia-container-toolkit repository key
  get_url:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    dest: /tmp/libnvidia-container-keyring.gpg

# otherwide next task will prompt for confirmation
- name: make sure nvidia-container-toolkit repository key does not already exist
  file:
    path: /usr/share/keyrings/libnvidia-container-keyring.gpg
    state: absent

- name: add nvidia-container-toolkit repository key to apt keyring
  shell: gpg --dearmor -o /usr/share/keyrings/libnvidia-container-keyring.gpg /tmp/libnvidia-container-keyring.gpg

- name: add nvidia-container-toolkit repository to sources list
  lineinfile:
    path: /etc/apt/sources.list.d/libnvidia-container-toolkit.list
    line: "deb [signed-by=/usr/share/keyrings/libnvidia-container-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /"
    create: yes

# crio runtime issues with prior versions, thus >= 1.14
- name: install nvidia-container-toolkit
  apt:
    name: "{{ packages }}"
    update_cache: true
    state: present
  vars:
    packages:
    - nvidia-container-toolkit

# https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#configuring-cri-o
# https://github.com/NVIDIA/k8s-device-plugin?tab=readme-ov-file#notes-on-cri-o-configuration
- name: set nvidia-container-runtime as the default low-level oci runtime
  shell: >
    nvidia-ctk runtime configure 
    --runtime=crio 
    --set-as-default 
    --config=/etc/crio/crio.conf.d/99-nvidia.conf

- name: add crun to the list of runtimes
  lineinfile:
    path: /etc/nvidia-container-runtime/config.toml
    regexp: '^runtimes ='
    line: 'runtimes = ["crun", "docker-runc", "runc"]'

- name: install conmon
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - conmon

- name: create symlink for /usr/libexec/crio/conmon in /usr/bin
  file:
    src: /usr/libexec/crio/conmon
    dest: /usr/bin/conmon
    state: link
    force: yes

- name: restart cri-o service
  systemd_service:
    name: crio
    state: restarted
