---
- name: uninstall nvidia device plugin
  kubernetes.core.helm:
    name: nvidia-device-plugin
    chart_ref: nvdp/nvidia-device-plugin
    namespace: nvidia-device-plugin
    state: absent

- name: remove nvidia device plugin namespace
  kubernetes.core.k8s:
    name: nvidia-device-plugin
    kind: Namespace
    state: absent

- name: remove nvidia device plugin helm repository
  kubernetes.core.helm_repository:
    name: nvdp
    state: absent
