---
- name: Install packages needed to use community.kubernetes collection
  block:
  - name: Install python3-pip
    apt:
      name: python3-pip
      state: present
      update_cache: yes

  - name: Install openshift Python package
    pip:
      name: openshift
      state: present

- name: Populate service facts
  service_facts:

- name: Ensure kubelet is not running
  service_facts:
  until:
  - ansible_facts['services']['kubelet.service']['state'] != 'running'
  retries: 2
  delay: 5
  failed_when: false

# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
- name: Initialize the k8s cluster
  shell: >
    kubeadm init 
    --apiserver-advertise-address={{ apiserver_advertise_address }} 
    --pod-network-cidr={{ pod_network_cidr }}
    --cri-socket={{ cri_socket }}
    --apiserver-cert-extra-sans={{ apiserver_cert_extra_sans }}
  when:
  - ansible_facts['services']['kubelet.service']['state'] != 'running'

- name: Create ~/.kube diectory
  become: no
  file:
    path: $HOME/.kube
    state: directory

- name: Copy k8s config file in ~/.kube
  copy:
    src: /etc/kubernetes/admin.conf
    remote_src: yes
    dest: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create /etc/default/kubelet to set --node-ip
  lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ kubelet_node_ip }}
    create: true

- name: Restart service kubelet
  systemd:
    daemon_reload: yes
    name: kubelet
    state: restarted
