---
- name: Install packages needed to use custom apt repositories
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - apt-utils
    - ca-certificates
    - curl
    - gpg
