---
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
- name: Disable swap
  shell: swapoff -a

- name: Download k8s public signing key
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/{{kubernetes_version_repo}}/{{kubernetes_os}}/Release.key
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Add k8s apt repository
  apt_repository:
    repo: |
      deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] 
      https://pkgs.k8s.io/core:/stable:/{{kubernetes_version_repo}}/{{kubernetes_os}}/ /
    filename: kubernetes
    state: present

- name: Install kubelet, kubeadm, and kubectl
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - kubelet={{ kubernetes_version_pkg }}
    - kubeadm={{ kubernetes_version_pkg }}
    - kubectl={{ kubernetes_version_pkg }}
