---
- name: uninstall flannel
  become: no
  kubernetes.core.helm:
    name: flannel
    chart_ref: flannel/flannel
    namespace: flannel
    state: absent

- name: delete flannel helm repository
  become: no
  kubernetes.core.helm_repository:
    name: flannel
    state: absent

- name: delete flannel namespace
  become: no
  kubernetes.core.k8s:
    name: flannel
    api_version: v1
    kind: Namespace
    state: absent

- name: delete flannel.1 interface
  shell: ip link delete flannel.1
  register: del_flannel
  failed_when:
  - del_flannel.rc != 0
  - "'Cannot find device \"flannel.1\"' not in del_flannel.stderr"
  changed_when:
  - del_flannel.rc == 0

- name: delete cni0 bridge
  shell: ip link delete cni0 type bridge
  register: del_cni
  failed_when:
  - del_cni.rc != 0
  - "'Cannot find device \"cni0\"' not in del_cni.stderr"
  changed_when:
  - del_cni.rc == 0

- name: delete /run/flannel
  file:
    path: /run/flannel
    state: absent
